[package]
edition = "2021"
name = "monotonic-test-stress"
version = "0.1.0"

[dependencies]
shared = {path = "../shared", features = ["rtic", "neopixels"]}

[features]
clock1k = ["shared/clock1k"]
clock32k = ["shared/clock32k"]
debug = ["shared/debug"]
neopixels = []
systick = ["shared/systick"]
