[package]
edition = "2021"
name = "monotonic-count-sequence"
version = "0.1.0"

[dependencies]
shared = {path = "../shared", features = ["rtic"]}

[features]
clock1k = ["shared/clock1k"]
clock32k = ["shared/clock32k"]
debug = ["shared/debug"]
systick = ["shared/systick"]
